### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#67]
**Must have (this is delta from what we have today)**
- [x] Change "performance" to "conformance" experiment
- [x] More test coverage
- [x] Target acquisition
  - [x] Finalizer
- [x] Stage of the experiment reflected in the Status
- [x] Simplification of status setting

**Nice to have (this is delta from what we have today)**
- [ ] Use DEFAULTS_FILE instead of DEFAULTS_DIR #50 
- [ ] Further flowchart alignment
- [ ] iter8ctl needs to show current weights

**Comment by kalantar** [comment]
Since required issues are done, closing this.
